import type { SiteConfig } from "@/types/config";

export const skillsPageConfig: SiteConfig["projectSection"]["skills"] = {
	enable: true,
	slug: "/skills/",
	navLabel: "Skills",
	title: "Skills",
	subtitle: "A data-oriented skill map focused on technical depth, interdisciplinary execution, and evidence that matters in selective admissions.",
	items: [
		{
			id: "ts-product",
			name: "TypeScript Product Engineering",
			category: "Engineering",
			description: "Builds maintainable front-end and full-stack product systems with strong UI sensitivity and shipping speed.",
			level: "expert",
			score: 92,
			icon: "fa6-brands:js",
			color: "#60A5FA",
			experience: { years: 3, months: 6 },
			relatedProjects: ["Atlas Research Copilot", "Moonshot Student Ops Dashboard"],
			proofs: [
				{ label: "Projects Shipped", value: "12" },
				{ label: "Largest Codebase", value: "25k LOC" },
			],
		},
		{
			id: "ai-systems",
			name: "AI Prototyping",
			category: "AI",
			description: "Rapidly designs and evaluates LLM workflows, retrieval systems, and application-level research tooling.",
			level: "advanced",
			score: 88,
			icon: "fa6-solid:brain",
			color: "#22D3EE",
			experience: { years: 2, months: 4 },
			relatedProjects: ["Atlas Research Copilot", "Narrative Portfolio Engine"],
			proofs: [
				{ label: "LLM Workflows", value: "20+" },
				{ label: "Evaluated Prompts", value: "500+" },
			],
		},
		{
			id: "ui-design",
			name: "Interface & Narrative Design",
			category: "Design",
			description: "Combines layout, visual systems, information hierarchy, and motion to make technical work legible and compelling.",
			level: "advanced",
			score: 86,
			icon: "fa6-solid:palette",
			color: "#38BDF8",
			experience: { years: 4, months: 0 },
			proofs: [
				{ label: "Portfolio Pages", value: "40+" },
				{ label: "Design Systems", value: "6" },
			],
		},
		{
			id: "research-writing",
			name: "Research Communication",
			category: "Writing",
			description: "Turns technical and academic work into concise, evidence-backed writing for judges, mentors, and admissions readers.",
			level: "advanced",
			score: 84,
			icon: "fa6-regular:file-lines",
			color: "#A78BFA",
			experience: { years: 2, months: 8 },
			proofs: [
				{ label: "Research Summaries", value: "70+" },
				{ label: "Pitch Decks", value: "18" },
			],
		},
		{
			id: "algorithmic-thinking",
			name: "Algorithmic Thinking",
			category: "CS Foundations",
			description: "Applies data structures, optimization, and contest-style reasoning to solve complex problems under time constraints.",
			level: "advanced",
			score: 82,
			icon: "fa6-solid:square-root-variable",
			color: "#F59E0B",
			experience: { years: 3, months: 0 },
			certifications: ["USACO Gold"],
			proofs: [
				{ label: "Problems Solved", value: "700+" },
				{ label: "Contest Seasons", value: "4" },
			],
		},
		{
			id: "leadership",
			name: "Team Leadership & Execution",
			category: "Leadership",
			description: "Leads interdisciplinary teams by setting milestones, reviewing work, and keeping product and narrative quality aligned.",
			level: "advanced",
			score: 85,
			icon: "fa6-solid:people-group",
			color: "#34D399",
			experience: { years: 2, months: 6 },
			proofs: [
				{ label: "Teams Led", value: "8" },
				{ label: "Collaborators", value: "35+" },
			],
		},
	],
};
