import type { SiteConfig } from "@/types/config";

export const timelinePageConfig: SiteConfig["projectSection"]["timeline"] = {
	enable: true,
	slug: "/timeline/",
	navLabel: "Timeline",
	title: "Timeline",
	subtitle: "A milestone timeline that emphasizes trajectory, leadership growth, competitions, research, and shipped work.",
	entries: [
		{
			id: "moonshot-academy",
			title: "Moonshot Academy",
			type: "education",
			startDate: "2023-09-01",
			location: "Beijing / Global",
			organization: "Moonshot Academy",
			role: "High School Student",
			description: "Pursuing a project-based high school track with strong emphasis on technical execution, interdisciplinary inquiry, and original work.",
			highlights: ["Independent project cycles", "Global application portfolio development"],
			skills: ["Research", "Product Thinking", "Writing"],
			featured: true,
			color: "#60A5FA",
		},
		{
			id: "usaco-gold",
			title: "Reached USACO Gold",
			type: "achievement",
			startDate: "2024-12-01",
			location: "Online",
			description: "Advanced to the Gold division through consistent algorithmic training and contest practice.",
			highlights: ["700+ problems solved", "4 contest seasons of preparation"],
			skills: ["Algorithms", "Data Structures", "Competitive Programming"],
			color: "#F59E0B",
		},
		{
			id: "atlas-research-copilot",
			title: "Built Atlas Research Copilot",
			type: "project",
			startDate: "2025-02-01",
			endDate: "2025-09-01",
			location: "Moonshot Academy",
			organization: "Independent Project",
			role: "Founder / Full-Stack Builder",
			description: "Designed and shipped an AI-native research workspace for faster literature review and experiment synthesis.",
			highlights: ["240+ users", "12k+ papers indexed", "63% review time saved"],
			skills: ["TypeScript", "Python", "RAG", "Systems Design"],
			links: [{ label: "Repository", url: "https://github.com/MRH0420" }],
			featured: true,
			color: "#22D3EE",
		},
		{
			id: "conrad-shortlist",
			title: "Conrad Challenge Shortlist",
			type: "achievement",
			startDate: "2025-05-01",
			location: "International",
			description: "Recognized for innovation quality and presentation strength in a globally competitive challenge environment.",
			highlights: ["Shortlisted project presentation", "Cross-disciplinary innovation framing"],
			skills: ["Pitching", "Innovation", "Presentation"],
			color: "#A78BFA",
		},
		{
			id: "ops-dashboard",
			title: "Launched Student Ops Dashboard",
			type: "project",
			startDate: "2025-08-01",
			endDate: "2025-12-01",
			location: "Moonshot Academy",
			organization: "Student Team Infrastructure",
			role: "Product Lead",
			description: "Built an operations dashboard for student teams to manage milestones, execution, and communication.",
			highlights: ["18 teams supported", "31% task completion lift"],
			skills: ["Product", "Astro", "PostgreSQL", "Design Systems"],
			color: "#34D399",
		},
		{
			id: "portfolio-engine",
			title: "Started Narrative Portfolio Engine",
			type: "research",
			startDate: "2026-01-01",
			location: "Independent Research",
			description: "Researching how to structure extracurricular evidence into reusable narrative systems for selective admissions.",
			highlights: ["45+ story modules", "12 portfolio variants"],
			skills: ["Prompt Design", "Writing", "Information Architecture"],
			featured: true,
			color: "#F472B6",
		},
	],
};
